### ISSUE TITLE
Make` MAX_SEQ_LEN` in request.py editable

### ISSUE THREAD

**Issue by stichiboi** [lightonai/paradigm-client#10]
In `request.py` there is a constant
```python
MAX_SEQ_LEN = 2048
```
 which is used in the `@validator` of the parameters.

If using a model with longer context length, this becomes a problem to use.

I've tried overriding the validator with a children class, but it doesn't seem to be possible with `pydantic` v1 (it's kinda possible with the v2, when using `root_validator` instead of `validator`)

Perhaps the best option would be to have the the `MAX_SEQ_LEN` load from an `env` variable (and default to 2048).

Happy to make a PR

**Comment by iacolippo** [comment]
Hey Daniele,

Good point. Something like `MAX_SEQ_LEN = int(os.environ.get("MAX_SEQ_LEN", 2048))` would do the job I guess

**Comment by iacolippo** [comment]
fixed on master a1ce94448610ef4043bc8cc3505c12e2d26407a3
